apiVersion: core.matrixorigin.io/v1alpha1
kind: MatrixOneCluster
metadata:
  name: {{ include "matrixone.fullname" . }}
  labels:
    {{- include "matrixone.labels" . | nindent 4 }}
{{- with .Values.spec }}
spec:
  {{- toYaml . | nindent 2 }}
{{- end }}
