name: build_binary
description: "test multi platform build binary"

runs:
  using: "composite"

  steps:
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: setup env
      uses: ./.github/actions/dev_env

    - name: build binary
      shell: bash
      run: make manager
