# Default values for matrixone-operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


########################################
#         openkruise                   #
########################################
crds:
  managed: true

# values for kruise installation
installation:
  namespace: kruise-system
  createNamespace: true
  roleListGroups:
    - '*'

featureGates: ""

manager:
  # settings for log print
  log:
    # log level for kruise-manager
    level: "4"

  replicas: 2
  image:
    repository: openkruise/kruise-manager
    tag: v1.2.0
  webhook:
    port: 9876
  metrics:
    port: 8080
  healthProbe:
    port: 8000
  pprofAddr: "localhost:8090"

  resyncPeriod: "0"

  # resources of kruise-manager container
  resources: {}
#    limits:
#      cpu: 200m
#      memory: 512Mi
#    requests:
#      cpu: 100m
#      memory: 256Mi

  hostNetwork: false

  nodeAffinity: {}
  nodeSelector: {}
  tolerations: []

webhookConfiguration:
  failurePolicy:
    pods: Ignore
  timeoutSeconds: 30

daemon:
  log:
    # log level for kruise-daemon
    level: "4"

  port: 10221
  pprofAddr: "localhost:10222"

  socketLocation: "/var/run"
  socketFile: ""

  nodeSelector: {}
  resources:
    limits:
      cpu: 50m
      memory: 128Mi
    requests:
      cpu: "0"
      memory: "0"

########################################
#        matrixone operator            #
########################################
env:
  RECONCILE_WAIT: "10s"            # Reconciliation delay
  WATCH_NAMESPACE: ""              # Namespace to watch or empty string to watch all namespaces

replicaCount: 1

image:
  repository: wanglei1995/matrixone-operator
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "test"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

rbac:
  create: true

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
