queue_rules:
  - name: shared_queue
    conditions:
      # Must write expected checks explicitly
      # Reference: https://docs.mergify.com/conditions/#validating-all-status-checks
      - check-success=e2e_kind_test
      - check-success=helm_pkg_check

pull_request_rules:
  - name: put pr to queue
    conditions:
      - "#approved-reviews-by>=1"
      - "#review-requested=0"
      - "#changes-requested-reviews-by=0"
    actions:
      queue:
        name: shared_queue
        method: squash

  - name: ping author on conflicts
    conditions:
      - conflict
    actions:
      comment:
        message: |
          This pull request has merge conflicts that must be resolved before it can be merged. @{{author}} please update it.
          Try `@mergify update` or update manually.

  - name: Notify author on queue failure
    conditions:
      - 'check-failure=Queue: Embarked in merge train'
    actions:
      comment:
        message: >
          Hey @{{ author }}, this pull request failed to merge and has been
          dequeued from the merge train.  If you believe your PR failed in
          the merge train because of a flaky test, requeue it by commenting
          with `@mergifyio requeue`.
          More details can be found on the `Queue: Embarked in merge train`
          check-run.

  - name: Welcome new contributor
    conditions:
      - author!=Mergify
    actions:
      comment:
        message: |
          Thanks for the contribution!
          Please review the labels and make any necessary changes.

  - name: ask for reviewing  PR
    conditions:
      - author!=Mergify
    actions:
      request_reviews:
        users:
          - wanglei4687
          - sukki37

  - name: PR label to need-review
    conditions:
      - check-success=e2e_kind_test
      - check-success=helm_pkg_check
      - label!=reviwed
    actions:
      label:
        add:
          - need-review

  - name: label on reviewed
    conditions:
      - "approved-reviews-by>=1"
      - "#review-requested=0"
      - "#changes-requested-reviews-by=0"
      - label=need-review
    actions:
      comment:
        message: "@{{ author }} this pull request is reviewed"
      label:
        add:
          - reviewed
        remove:
          - need-review

  - name: label on Feature
    conditions:
      - body~=(?m)- \[(?i)x\] Feature
    actions:
      label:
        add:
          - feature

  - name: label on Bug Fix
    conditions:
      - body~=(?m)- \[(?i)x\] Bug
    actions:
      label:
        add:
          - bug

  - name: label on Improvement
    conditions:
      - body~=(?m)^- \[(?i)x\] Improvement
    actions:
      label:
        add:
          - improvement

  - name: label on Test and CI
    conditions:
      - body~=(?m)^- \[(?i)x\] Test and CI
    actions:
      label:
        add:
          - test-ci

  - name: label on Code Refactoring
    conditions:
      - body~=(?m)^- \[(?i)x\] Code Refactoring
    actions:
      label:
        add:
          - code-refactoring

  - name: label on Documentation
    conditions:
      - body~=(?m)^- \[(?i)x\] Documentation
    actions:
      label:
        add:
          - doc

  - name: label on API-change
    conditions:
      - body~=(?m)- \[(?i)x\] API-change
    actions:
      label:
        add:
          - api-change
