run:
  timeout: 30m
  skip-files:
    - "^zz_generated.*"

output:
  sort-results: true

linters:
  disable-all: true
  # https://golangci-lint.run/usage/linters/#enabled-by-default-linters
  enable:
    - revive
    - staticcheck
    - errcheck


issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck

linters-settings:
  staticcheck:
    go: "1.18"
    # https://staticcheck.io/docs/configuration/options/#checks
    checks: [
    "all",
    "-S1*",
    "-ST1*",
    "-SA5011",
    "-SA1019",
    "-SA2002"
    ]

  unused:
    go: "1.18"
