run: 
  deadline: 10m

output:
   format: json
   sort-results: true

linters:
  enable:
    - revive
    - asciicheck
    - nilerr
    - gosec

issues:
  exclude-rules:
  - path: _test\.go
    linters:
      - errcheck
  - linters:
    - lll
    source: "^//go:generate "
  - linters:
    - staticcheck
    text: "SA9003:"

linters-settings:
  errcheck:
    exclude: scripts/errcheck_excludes.txt
