run:
  concurrency: 4
  timeout: 30m
  go: '1.19'
  skip-files:
    - "^zz_generated.*"

output:
  sort-results: true

linters:
  disable-all: true
  enable:
    - revive

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck

linters-settings:
  staticcheck:
    go: "1.19"
    checks: [
      "all",
      "-S1*",
      "-ST1*",
      "-SA5011",
      "-SA1019",
      "-SA2002"
    ]
  unused:
    go: "1.19"
