run:
  timeout: 30m
  concurrency: 2
  modules-download-mode: readonly
  go: '1.18'
  skip-files:
    - "^zz_generated.*"

output:
  sort-results: true

linters:
  disable-all: true
  # https://golangci-lint.run/usage/linters/#enabled-by-default-linters
  enable:
    - revive
    - staticcheck
    - unused

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - revive

linters-settings:
  staticcheck:
    # https://staticcheck.io/docs/configuration/options/#checks
    checks: [
      "all",
      "-S1*",
      "-ST1*",
      "-SA5011",
      "-SA1019",
      "-SA2002"
    ]
