version: "2"
run:
  go: "1.23"
linters:
  default: none
  enable:
    - revive
  settings:
    revive:
      rules:
        - name: unused-parameter
          arguments:
            - allowRegex: ^_
          severity: warning
          disabled: false
    staticcheck:
      checks:
        - all
        - -S1*
        - -SA1019
        - -SA2002
        - -SA5011
        - -ST1*
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - errcheck
        path: _test\.go
    paths:
      - ^zz_generated.*
      - third_party$
      - builtin$
      - examples$
formatters:
  exclusions:
    generated: lax
    paths:
      - ^zz_generated.*
      - third_party$
      - builtin$
      - examples$
