run: 
  deadline: 10m

linters:
  enable:
    - revive

issues:
  exclude-rules:
  - path: _test\.go
    linters:
      - errcheck
      - gosec
  - linters:
    - lll
    source: "^//go:generate "
  - linters:
    - staticcheck
    text: "SA9003:"

linters-settings:
  errcheck:
    exclude: scripts/errcheck_excludes.txt
