header:
  license:
    spdx-id: Apache-2.0
    copyright-owner: Matrix Origin
  paths-ignore:
    - 'docs/'
    - 'examples/'
    - '.golangci.yml'
    - '.gitatrributes'
    - '.gitignore'
    - '.codeenv.yml'
    - '.github/'
    - '**/*.md'
    - 'LICENSE'
    - '.editorconfig'
    - 'packages/'
    - 'charts/'
    - 'hack/'
    - 'images/'
    - '**/*.yml'
    - '**/*.yaml'
    - 'Makefile'
    - 'PROJECT'
    - '**/go.mod'
    - '**/go.sum'
    - 'deploy/'
    - 'third_part/'
    - '**/Dockerfile'
  comment: on-failure
