name: kind_cluster
description: "bootstrap a kind cluster"

runs:
  using: "composite"

  steps:
    - name: pre_env
      uses: ./.github/actions/dev_env

    - name: start KinD
      uses: engineerd/setup-kind@v0.5.0
      with:
        version: ${{ env.kind-version }}
        image: ${{ env.kind-image }}
        wait: 300s
        config: /test/kind-config.yml

    - name: load kind rbac policy
      shell: bash
      run: |
        kubectl apply -f test/kind-rbac.yml

    - name: prepare images
      shell: bash
      run: |
        export DOCKER_BUILDKIT=1
        make op-build bvt-build

    - name: load images to cluster
      shell: bash
      run: |
        kind load docker-image matrixorigin/matrixone-operator:latest
        kind load docker-image matrixorigin/mysql-tester:latest

    - name: wait for cluster to finish bootstraping
      shell: bash
      run: |
        kubectl wait --for=condition=Ready pods --all --all-namespaces --timeout=300s
        kubectl cluster-info
        kubectl get pods -A
