//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2021.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	corev1 "k8s.io/api/core/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MatrixoneCluster) DeepCopyInto(out *MatrixoneCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MatrixoneCluster.
func (in *MatrixoneCluster) DeepCopy() *MatrixoneCluster {
	if in == nil {
		return nil
	}
	out := new(MatrixoneCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MatrixoneCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MatrixoneClusterList) DeepCopyInto(out *MatrixoneClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MatrixoneCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MatrixoneClusterList.
func (in *MatrixoneClusterList) DeepCopy() *MatrixoneClusterList {
	if in == nil {
		return nil
	}
	out := new(MatrixoneClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MatrixoneClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MatrixoneClusterSpec) DeepCopyInto(out *MatrixoneClusterSpec) {
	*out = *in
	if in.Services != nil {
		in, out := &in.Services, &out.Services
		*out = make([]corev1.Service, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MatrixoneClusterSpec.
func (in *MatrixoneClusterSpec) DeepCopy() *MatrixoneClusterSpec {
	if in == nil {
		return nil
	}
	out := new(MatrixoneClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MatrixoneClusterStatus) DeepCopyInto(out *MatrixoneClusterStatus) {
	*out = *in
	out.MatrixoneNodeStatus = in.MatrixoneNodeStatus
	if in.Statefulset != nil {
		in, out := &in.Statefulset, &out.Statefulset
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Deployment != nil {
		in, out := &in.Deployment, &out.Deployment
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Services != nil {
		in, out := &in.Services, &out.Services
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ConfigMaps != nil {
		in, out := &in.ConfigMaps, &out.ConfigMaps
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PodDisruptionBudgets != nil {
		in, out := &in.PodDisruptionBudgets, &out.PodDisruptionBudgets
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Ingress != nil {
		in, out := &in.Ingress, &out.Ingress
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.HPAutoScalers != nil {
		in, out := &in.HPAutoScalers, &out.HPAutoScalers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Pods != nil {
		in, out := &in.Pods, &out.Pods
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PersistentVolumeClaims != nil {
		in, out := &in.PersistentVolumeClaims, &out.PersistentVolumeClaims
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MatrixoneClusterStatus.
func (in *MatrixoneClusterStatus) DeepCopy() *MatrixoneClusterStatus {
	if in == nil {
		return nil
	}
	out := new(MatrixoneClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MatrixoneNodeTypeStatus) DeepCopyInto(out *MatrixoneNodeTypeStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MatrixoneNodeTypeStatus.
func (in *MatrixoneNodeTypeStatus) DeepCopy() *MatrixoneNodeTypeStatus {
	if in == nil {
		return nil
	}
	out := new(MatrixoneNodeTypeStatus)
	in.DeepCopyInto(out)
	return out
}
