# Default values for kruise.

crds:
  managed: true

# values for kruise installation
installation:
  namespace: kruise-system
  createNamespace: true
  roleListGroups:
    - '*'

featureGates: ""

# KUBE_CACHE_MUTATION_DETECTOR
enableKubeCacheMutationDetector: false

manager:
  # settings for log print
  log:
    # log level for kruise-manager
    level: "4"

  replicas: 2
  image:
    repository: openkruise/kruise-manager
    tag: v1.4.0
  webhook:
    port: 9876
  metrics:
    port: 8080
  healthProbe:
    port: 8000
  pprofAddr: "localhost:8090"

  resyncPeriod: "0"

  # resources of kruise-manager container
  resources:
    limits:
      cpu: 200m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi

  hostNetwork: false

  nodeAffinity: {}
  nodeSelector: {}
  tolerations: []

  # set serviceAccountName to set permissions externally
  serviceAccountName: ""

webhookConfiguration:
  enabled: true
  failurePolicy:
    pods: Ignore
  timeoutSeconds: 30

daemon:
  log:
    # log level for kruise-daemon
    level: "4"

  port: 10221
  pprofAddr: "localhost:10222"

  socketLocation: "/var/run"
  socketFile: ""

  nodeSelector: {}
  resources:
    limits:
      cpu: 50m
      memory: 128Mi
    requests:
      cpu: "0"
      memory: "0"
  # set serviceAccountName to set permissions externally
  serviceAccountName: ""

  # Extra environment variables that will be pass onto pods.
  # For example, when the daemon is used behind a http proxy, you can set the proxy environment variables here.
  # This will be appended to the current 'env:' key. You can use any of the kubernetes env
  # syntax here.
  extraEnvs: []
  # - name: HTTP_PROXY
  #   value: http://my-proxy:8080/
  # - name: HTTPS_PROXY
  #   value: http://my-proxy:8080/
  # - name: NO_PROXY
  #   value: localhost,0.0.0.0,127.0.0.1,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,.svc,.cluster.local

serviceAccount:
  annotations: {}

imagePullPolicy: IfNotPresent
