# permissions for end users to view matrixoneclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: matrixonecluster-viewer-role
rules:
- apiGroups:
  - matrixone.matrixorigin.cn
  resources:
  - matrixoneclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - matrixone.matrixorigin.cn
  resources:
  - matrixoneclusters/status
  verbs:
  - get
