# permissions for end users to view matrixones.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: matrixone-viewer-role
rules:
- apiGroups:
  - matrixone.matrixorigin.cn
  resources:
  - matrixones
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - matrixone.matrixorigin.cn
  resources:
  - matrixones/status
  verbs:
  - get
