
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - matrixone.matrixorigin.cn
  resources:
  - matrixoneclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - matrixone.matrixorigin.cn
  resources:
  - matrixoneclusters/status
  verbs:
  - get
  - patch
  - update
