apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
networking:
  serviceSubnet: "10.96.0.0/12"
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 6001
        hostPort: 6001
  - role: worker
  - role: worker
  - role: worker
