kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
featureGates:
  "CSIMigration": true
runtimeConfig:
  "api/alpha": "false"
networking:
  serviceSubnet: "10.96.0.0/12"
node:
  - role: control-plane
    extraPortMappings:
      - containerPort: 6001
        hostPort: 6001
  - role: worker
  - role: worker
  - role: worker
