apiVersion: v1
kind: ConfigMap
metadata:
  name: mo-cfg
data:
  config.toml: |
        rootpassword = ""
        dumpdatabase = "default"
        port = 6000
        host = "0.0.0.0"
        sendRow = false
        dumpEnv = false
        hostMmuLimitation = 1099511627776
        guestMmuLimitation = 1099511627776
        mempoolMaxSize = 1099511627776
        mempoolFactor = 8
        processLimitationSize = 42949672960
        processLimitationBatchRows = 42949672960
        processLimitationBatchSize = 0
        processLimitationPartitionRows = 42949672960
        countOfRowsPerSendingToClient = 10
        periodOfEpochTimer = 5
        periodOfPersistence = 20
        periodOfDDLDeleteTimer = 20
        timeoutOfHeartbeat = 20
        rejectWhenHeartbeatFromPDLeaderIsTimeout = false
        enableEpochLogging = false
        recordTimeElapsedOfSqlRequest = true
        cubeDirPrefix = "./cube"
        prophetEmbedEtcdJoinAddr = "http://localhost:40000"
        maxReplicas = 1
        lengthOfQueryPrinted = 50
        batchSizeInLoadData = 40000
        loadDataConcurrencyCount = 16
        cubeLogLevel = "error"
        cubeMaxEntriesBytes = 314572800
        pre-allocated-group-num = 20
        max-group-num           = 0
        level = "info"
        format = "json"
        filename = "./log/mo.log"
        max-size = 512
        max-days = 0
        max-backups = 10
        addr-raft = "172.19.0.2:10000"
        addr-client = "172.19.0.2:20000"
        dir-data = "./cube/node"
        dir-deploy = ""
        version = ""
        githash = ""
        capacity = 0
        use-memory-as-storage = false
        shard-groups = 2
        [replication]
          max-peer-down-time = "30m"
          shard-split-check-duration = "30s"
          shard-state-check-duration = "1m"
          disable-shard-split = false
          allow-remove-leader = false
          shard-capacity-bytes = "96MB"
          shard-split-check-bytes = "64MB"
        [snapshot]
          max-concurrency-snap-chunks = 8
          snap-chunk-size = "4MB"
        [raft]
          enable-pre-vote = true
          tick-interval = "1s"
          heartbeat-ticks = 2
          election-timeout-ticks = 10
          max-size-per-msg = 0
          max-inflight-msgs = 512
          max-entry-bytes = 314572800
          send-raft-batch-size = 64
        [raft.raft-log]
          disable-sync = false
          compact-duration = "30s"
          compact-threshold = 256
          max-allow-transfer-lag = 2
          ForceCompactCount = 0
          ForceCompactBytes = 0
          CompactProtectLag = 0
        [worker]
          raft-apply-worker = 32
          raft-msg-worker = 8
          raft-event-worker = 32
        [prophet]
          name = "node0"
          data-dir = ""
          rpc-addr = "172.19.0.2:30000"
          rpc-timeout = "10s"
          storage-node = true
          external-etcd = [""]
          lease = 3
        [prophet.embed-etcd]
          join = ""
          client-urls = "http://172.19.0.2:40000"
          peer-urls = "http://172.19.0.2:50000"
          advertise-client-urls = ""
          advertise-peer-urls = ""
          initial-cluster = ""
          initial-cluster-state = ""
          tick-interval = "500ms"
          election-interval = "3000ms"
          enable-prevote = true
          auto-compaction-mode = "periodic" 
          auto-compaction-retention = "1h"
          quota-backend-bytes = "8GB"
        [prophet.schedule]
          max-snapshot-count = 3
          max-pending-peer-count = 16
          max-merge-resource-size = 0
          max-merge-resource-keys = 0
          split-merge-interval = "0s"
          enable-one-way-merge = false
          enable-cross-table-merge = false
          patrol-resource-interval = "100ms"
          max-container-down-time = "30m"
          leader-schedule-limit = 4
          leader-schedule-policy = "count"
          resource-schedule-limit = 2048
          replica-schedule-limit = 64
          merge-schedule-limit = 0
          hot-resource-schedule-limit = 4
          hot-resource-cache-hits-threshold = 3
          tolerant-size-ratio = 0.0
          low-space-ratio = 0.8   
          high-space-ratio = 0.7
          resource-score-formula-version = ""
          scheduler-max-waiting-operator = 5
          enable-remove-down-replica = true
          enable-replace-offline-replica = true
          enable-make-up-replica = true
          enable-remove-extra-replica = true
          enable-location-replacement = true
          enable-debug-metrics = false
          enable-joint-consensus = true
          container-limit-mode = ""
        [prophet.replication]
          max-replicas = 3
          strictly-match-label = true
          enable-placement-rules = true
          isolation-level = "rack"
        [metric]
          addr = ""
          interval = 0
          job = ""
          instance = ""
        [meta.conf]
          block-max-rows = 40000
          segment-max-blocks = 40
        [scheduler-cfg]
          block-writers = 8
          segment-writers = 4
        [cache-cfg]
          index-cache-size = 134217728        
          insert-cache-size = 4294967296      
          data-cache-size = 4294967296 

