apiVersion: apps/v1
kind: Deployment
metadata:
  name: mo
  namespace: matrixone
spec:
  selector:
    matchLabels:
      app: mo
  template:
    metadata:
      labels:
        app: mo
    spec:
      containers:
      - name: mo
        image: matrixorigin/matrixone:latest
        resources:
          limits:
            memory: "2Gi"
            cpu: "500m"
        volumeMounts:
          - name: data
            mountPath: /cube
          - name: config
            mountPath:  /config
          - name: log
            mountPath: /log
        ports:
        - containerPort: 6001
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: mo-pvc
        - name: log
          persistentVolumeClaim:
            claimName: mo-pvc
        - name: config
          configMap:
            name: mo-cfg
