name: pre_env
description: "prepare actions env"

runs:
  using: "composite"

  steps:
    - name: import env variables
      shell: bash
      run: cat ".github/env" >> $GITHUB_ENV

    - name: setup go version
      uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # tag=v7.0.0
      with:
        check-latest: false
        go-version:
          ${{ env.golang-version }}
