name: pre_env
description: "prepare actions env"

runs:
  using: "composite"

  steps:
    - name: import env variables
      shell: bash
      run: cat ".github/env" >> $GITHUB_ENV

    - name: setup go version
      uses: actions/setup-go@v3
      with:
        # https://github.com/actions/go-versions/blob/main/versions-manifest.json
        go-version:
          ${{ env.golang-version }}
