apiVersion: matrixone.matrixorigin.cn/v1alpha1
kind: Matrixone
metadata:
  name: matrixone-standalone
spec:
  kubernetesConfig:
    image: "matrixorigin/matrixone:latest"
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 101m
        memory: 128Mi
      limits:
        cpu: 101m
        memory: 128Mi
    serviceType: ClusterIP
  storage:
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  matrixExporter:
    enabled: false
    image: 'matrixorigin/matirxone-exporter:latest'