name: e2e_kind
description: "operator kind e2e test"

runs:
  using: "composite"

  steps:
    - name: prepare cluster
      uses: ./.github/actions/cluster

    - name: Deploy Operator
      shell: bash
      run: |
        make deploy

    - name: Wait for operator to finish bootstraping
      shell: bash
      run: |
          kubectl wait --for=condition=Ready pods --all --all-namespaces --timeout=300s
          kubectl cluster-info
          kubectl get pods -A

    - name: Deploy cluster
      shell: bash
      run: |
        kubectl apply -f examples/tiny-cluster.yaml

    - name: Wait for mo cluster to finish bootstraping
      shell: bash
      run: |
          kubectl wait --for=condition=Ready pods --all --all-namespaces --timeout=600s
          kubectl cluster-info
          kubectl get pods -A

    - name: Run test
      shell: bash
      run:  |
        kubectl run bvt-tester --image=matrixorigin/mysql-tester -i --rm --restart=Never -- \
        -host mo.default.svc.cluster.local -port  6001 -user dump -passwd 111
