name: e2e_kind
description: "operator kind e2e test"

runs:
  using: "composite"

  steps:
    - name: prepare cluster
      uses: ./.github/actions/cluster

    - name: Deploy Operator
      shell: bash
      run: |
        make deploy

    - name: Run test
      shell: bash
      run:  |
        MYSQL_TEST_IMAGE=matrixorigin/mysql-tester:0.4.0 ./hack/e2e.sh
