name: checks
description: "check license header"
inputs:
  github_token:
    descirption: "Github Token"
    required: true

runs:
  using: "composite"

  steps:
    - name: pre_env
      uses: ./.github/actions/dev_env

    - name: check_license_header
      uses: apache/skywalking-eyes@main
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      with:
        log: info
        config: .github/licenserc.yml

    - name: golangci_lint
      uses: golangci/golangci-lint-action@v3.1.0
      with:
        version: v1.46.1
        args: --timeout 10m0s
