name: checks
description: "check license header"
inputs:
  github_token:
    description: "Github Token"
    required: true

runs:
  using: "composite"

  steps:
    - name: pre_env
      uses: ./.github/actions/dev_env

    - name: check_license_header
      uses: apache/skywalking-eyes/header@main
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      with:
        log: info
        config: .licenserc.yml

    - name: verify
      shell: bash
      run: make verify

    # disable action cache due to https://github.com/golangci/golangci-lint-action/issues/244
    - name: golangci_lint
      uses: golangci/golangci-lint-action@v3.2.0
      with:
        version: '${{ env.golangci-lint-version }}'
        args: --timeout 10m0s
        skip-cache: true
