name: checks
description: "check license header"
inputs:
  github_token:
    description: "Github Token"
    required: true

runs:
  using: "composite"

  steps:
    - name: pre_env
      uses: ./.github/actions/dev_env

    - name: check_license_header
      uses: apache/skywalking-eyes@main
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      with:
        log: info
        config: .licenserc.yml

    - uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - uses: actions/cache@v3
      with:
        path: |
          **/tmp/bin
        key: ${{ runner.os }}-tools-${{ hashFiles('**/tools/go.sum') }}

    - name: verify
      shell: bash
      run: make verify

    - name: golangci_lint
      uses: golangci/golangci-lint-action@v3.1.0
      with:
        version: v1.45.2
        args: --timeout 10m0s
