name: build_image
description: "test multi platform build"

runs:
  using: "composite"

  steps:
    - name: setup QEMU
      uses: docker/setup-qemu-action@master
      with:
        image: tonistiigi/binfmt:latest
        platforms: linux/amd64,linux/arm64

    - name: setup docker buildx
      id: buildx
      uses: docker/setup-buildx-action@v1


    - name: build image
      uses: docker/build-push-action@v2
      env:
        DOCKER_BUILDKIT: 1
      with:
        builder: ${{ steps.buildx.outputs.name }}
        context: .
        file: images/operator/Dockerfile
        platforms: linux/amd64,linux/arm64
        push: false
        tags: "test"
