apiVersion: core.matrixorigin.io/v1alpha1
kind: MatrixOneCluster
metadata:
  name: mo
spec:
  imageRepository: matrixorigin/matrixone
  version: 1.2.3
  logService:
    replicas: 3
    sharedStorage:
      s3:
        type: minio
        path: matrixone
        endpoint: http://minio.default:9000
        secretRef:
          name: minio
    volume:
      size: 10Gi
  tn:
    replicas: 1
    cacheVolume:
      size: 10Gi
  cnGroups:
  - name: tp
    replicas: 2
    cacheVolume:
      size: 10Gi
