apiVersion: core.matrixorigin.io/v1alpha1
kind: MatrixOneCluster
metadata:
  name: mo
spec:
  imageRepository: aylei/mo-service
  version: 0.1.7
  logService:
    resources:
      requests:
        cpu: 1
    initialConfig:
      logShards: 1
      dnShards: 1
      haKeeperReplicas: 3
      logShardReplicas: 3
    replicas: 3
    sharedStorage:
      s3:
        path: aylei-test/mo-logset
    volume:
      size: 10Gi
    nodeSelector:
      kubernetes.io/arch: amd64
  dn:
    replicas: 2
    cacheVolume:
      size: 10Gi
    nodeSelector:
      kubernetes.io/arch: amd64
  tp:
    replicas: 2
    cacheVolume:
      size: 10Gi
    nodeSelector:
      kubernetes.io/arch: amd64
