apiVersion: core.matrixorigin.io/v1alpha1
kind: MatrixOneCluster
metadata:
  name: mo
spec:
  imageRepository: matrixorigin/matrixone
  version: nightly-63835b83
  logService:
    replicas: 3
    sharedStorage:
      s3:
        path: maomao-moc-test/test
        secretRef:
          name: aws
    volume:
      size: 10Gi
  dn:
    replicas: 2
    # cacheVolume specifies a dedicated volume for DN's local cache
    cacheVolume:
      size: 10Gi
  tp:
    replicas: 2
    # cacheVolume specifies a dedicated volume for CN's local cache
    cacheVolume:
      size: 10Gi
