apiVersion: matrixone.matrixorigin.cn/v1alpha1
kind: MatrixoneCluster
metadata:
  name:  mo
spec:
  image: matrixorigin/matrixone:kc-0.3.0
  imagePullPolicy: IfNotPresent
  storageClass: cbs
  replicas: 3
  podName:
    name: POD_NAME
    valueFrom:
      fieldRef:
        fieldPath: metadata.name
  logVolumeCap: 10Gi
  dataVolumeCap: 10Gi
