apiVersion: matrixone.matrixorigin.cn/v1alpha1
kind: MatrixoneCluster
metadata:
  name: mo
spec:
  image: matrixorigin/matrixone:kc-0.3.0
  imagePullPolicy: IfNotPresent
  replicas: 3
  storageClass: standard
  requests:
    cpu: 200m
    memory: 300Mi
  limits:
    cpu: 200m
    memory: 300Mi
  podName:
    name: POD_NAME
    valueFrom:
      fieldRef:
        fieldPath: metadata.name
  logVolumeCap: 200Mi
  dataVolumeCap: 200Mi
