apiVersion: matrixone.matrixorigin.cn/v1alpha1
kind: MatrixoneCluster
metadata:
  name: mo
spec:
  image: wanglei1995/matrixone:kc
  image-pull-policy: Always
  replicas: 3
  storage-class: standard
  resources:
    limits:
      cpu: "500m"
      memory: "500Mi"
    requests:
      cpu: "500m"
      memory: "500Mi"
  pod-name: 
    name: POD_NAME
    valueFrom:
      fieldRef:
        fieldPath: metadata.name
  log-volume-resource: 
    requests:
      storage: 500Mi
  data-volume-resource:
    requests:
      storage: 500Mi
  

  
