apiVersion: matrixone.matrixorigin.cn/v1
kind: MatrixoneCluster
metadata:
  name: matrixonecluster-sample
spec:
  image: matrixorigin/matrixone:nightly
  replicas: 3
  storage-class: standard
  log-volume-resource: 
    requests:
      storage: 500Mi
  data-volume-resource: 
    requests:
      storage: 500Mi
  
