apiVersion: matrixone.matrixorigin.cn/v1alpha1
kind: MatrixoneCluster
metadata:
  name: mo
spec:
  image: wanglei1995/matrixone:kc
  imagePullPolicy: Always
  replicas: 3
  storageClass: gp2
  podName: 
    name: POD_NAME
    valueFrom:
      fieldRef:
        fieldPath: metadata.name
  logVolumeResource: 
    requests:
      storage: 300Mi
  dataVolumeResource:
    requests:
      storage: 300Mi
  

  
