apiVersion: matrixone.matrixorigin.cn/v1alpha1
kind: MatrixoneCluster
metadata:
  name: mo
spec:
  image: matrixorigin/matrixone:kc-0.3.0
  imagePullPolicy: Always
  replicas: 3
  storageClass: standard
  podName: 
    name: POD_NAME
    valueFrom:
      fieldRef:
        fieldPath: metadata.name
  logVolumeResource: 
    requests:
      storage: 500Mi
  dataVolumeResource:
    requests:
      storage: 500Mi
  

  
