apiVersion: matrixone.matrixorigin.cn/v1alpha1
kind: MatrixoneCluster
metadata:
  name: mo
spec:
  image: matrixorigin/matrixone:latest
  imagePullPolicy: IfNotPresent
  replicas: 3
  storageClass: standard
  podName:
    name: POD_NAME
    valueFrom:
      fieldRef:
        fieldPath: metadata.name
  logVolumeCap: 500Mi
  dataVolumeCap: 500Mi
