apiVersion: matrixone.matrixorigin.cn/v1alpha1
kind: MatrixoneCluster
metadata:
  name: mo
spec:
  image: wanglei1995/matrixone:kc
  imagePullPolicy: Always
  replicas: 3
  storageClass: standard
  resources:
    limits:
      cpu: "500m"
      memory: "500Mi"
    requests:
      cpu: "500m"
      memory: "500Mi"
  podName: 
    name: POD_NAME
    valueFrom:
      fieldRef:
        fieldPath: metadata.name
  logVolumeResource: 
    requests:
      storage: 500Mi
  dataVolumeResource:
    requests:
      storage: 500Mi
  