apiVersion: matrixone.matrixorigin.cn/v1alpha1
kind: MatrixoneCluster
metadata:
  name: mo
spec:
  image: matrixorigin/matrixone:0.4.0
  imagePullPolicy: Always
  replicas: 1
  requests:
    cpu: 200m
  podName:
    name: POD_NAME
    valueFrom:
      fieldRef:
        fieldPath: metadata.name
  logVolumeCap: 10Gi
  dataVolumeCap: 10Gi
