apiVersion: matrixone.matrixorigin.cn/v1alpha1
kind: MatrixoneCluster
metadata:
  name: mo
spec:
  image: wanglei1995/matrixone:kc
  replicas: 3
  storage-class: standard
  pod-name: 
    name: POD_NAME
    valueFrom:
      fieldRef:
        fieldPath: metadata.name
  log-volume-resource: 
    requests:
      storage: 500Mi
  data-volume-resource:
    requests:
      storage: 500Mi
  

  
