apiVersion: matrixone.matrixorigin.cn/v1alpha1
kind: MatrixoneCluster
metadata:
  name: mo
spec:
  image: matrixorigin/matrixone:kc-0.3.0
  image-pull-policy: IfNotPresent
  replicas: 3
  storage-class: standard
  pod-name: 
    name: POD_NAME
    valueFrom:
      fieldRef:
        fieldPath: metadata.name
  logVolumeResource: 
    requests:
      storage: 500Mi
  dataVolumeResource:
    requests:
      storage: 500Mi
  