apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mo0-data-pvc
  namespace: matrixone
spec:
  storageClassName: gp2
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mo0-log-pvc
  namespace: matrixone
spec:
  storageClassName: gp2
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi