@startuml

Pending: Wait depedencies
Reconciling: Continously Observe()
PendingFinalize: Marked to finalize, wait dependents deleted
Synced: Reach desired state
State...: Arbitrary extended state
Finalizing: Being finalized

[*] --> Pending: Create CR
Pending --> Pending: WaitDependencies()
Pending --> Reconciling: Depedencies Ready
Reconciling -right-> Synced: Observe()
Synced -left-> Reconciling: Watch / Resync
Reconciling -left-> State...: Observe()
State... -right-> Reconciling: ActionXXX()
Reconciling --> PendingFinalize: Delete CR
PendingFinalize --> PendingFinalize: WaitDependents()
PendingFinalize --> Finalizing: Dependents Deleted
Finalizing --> Finalizing: Finalize()
Finalizing --> [*]: Resources Finalized

@enduml