apiVersion: core.matrixorigin.io/v1alpha1
kind: MatrixOneCluster
metadata:
  name: mo
spec:
  imageRepository: matrixorigin/matrixone
  version: nightly-d4d009e9
  logService:
    replicas: 3
    sharedStorage:
      s3:
        type: minio
        path: matrixone/data
        endpoint: http://minio:9301
        secretRef:
          name: minio
    volume:
      size: 10Gi
  dn:
    replicas: 1
    cacheVolume:
      size: 10Gi
  tp:
    replicas: 1
    cacheVolume:
      size: 10Gi
  webui:
    replicas: 1
    updateStrategy:
      maxUnavailable: 25
