spec: {}

# debugger deploys a debugger pod to the k8s cluster that help troubleshooting the cluster problem
debugger:
  enabled: false
  image: ubuntu:latest
  imagePullPolicy: IfNotPresent
  imagePullSecrets: []
  resources: {}
  rules:
  - apiGroups:
    - "*"
    resources:
    - "*"
    verbs:
    - '*'
