name: e2e
description: "operator e2e test"
inputs:
  mo_version:
    description: "MO_VERSION"
    required: false

runs:
  using: "composite"

  steps:
    - name: pre_env
      uses: ./.github/actions/dev_env

    - name: setup helm
      uses: azure/setup-helm@9bc31f4ebc9c6b171d7bfbaa5d006ae7abdb4310 # tag=v5.0.1
      with:
        version: '${{ env.helm-version }}'

    - name: setup kind
      uses: helm/kind-action@ef37e7f390d99f746eb8b610417061a60e82a6cc # tag=v1.14.0
      with:
        install_only: true
        version: v0.15.0

    - name: Run kind test
      shell: bash
      env:
        MO_VERSION: ${{ inputs.mo_version }}
      run:  |
        make e2e-kind TAG=e2e-kind
