name: e2e
description: "operator e2e test"

runs:
  using: "composite"

  steps:
    - name: pre_env
      uses: ./.github/actions/dev_env

    - name: setup helm
      uses: azure/setup-helm@v1
      with:
        version: '${{ env.helm-version }}'

    - name: setup kind
      uses: engineerd/setup-kind@v0.5.0
      with:
        skipClusterCreation: true
        version: v0.15.0

    - name: Run test
      shell: bash
      run:  |
        make e2e
