{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "matrixone-operator.fullname" . }}
  labels:
    {{- include "matrixone-operator.labels" . | nindent 4 }}
rules:
  - apiGroups:
    - admissionregistration.k8s.io
    resources:
    - mutatingwebhookconfigurations
    - validatingwebhookconfigurations
    verbs:
    - get
    - update
    - list
    - patch
    - watch
  {{- if not .Values.onlyWatchReleasedNS }}
  - apiGroups:
      - ""
    resources:
      - pods
      - services
      - configmaps
      - secrets
      - persistentvolumeclaims
      - pods/status
      - pods/exec
    verbs:
      - '*'
  - apiGroups:
      - "apps"
    resources:
      - deployments
    verbs:
      - get
      - list
      - watch
      - create
      - patch
      - update
      - delete
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
  - apiGroups:
      - apps.kruise.io
    resources:
      - '*'
    verbs:
      - '*'
  - apiGroups:
      - policy.kruise.io
    resources:
      - '*'
    verbs:
      - '*'
  - apiGroups:
      - core.matrixorigin.io
    resources:
      - '*'
    verbs:
      - '*'
  - apiGroups:
      - coordination.k8s.io
    resources:
      - '*'
    verbs:
      - '*'
  - apiGroups:
      - 'batch'
    resources:
      - jobs
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  {{- end }}
{{- end }}
