{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "matrixone-operator.fullname" . }}
  labels:
    {{- include "matrixone-operator.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "matrixone-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ template "matrixone-operator.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
