apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: matrixone-operator-mutating-webhook-{{ .Release.Name }}
  annotations:
    matrixorigin.io/ca-injection: 'y'
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: '{{ .Release.Namespace }}'
      path: /mutate-core-matrixorigin-io-v1alpha1-cnset
  failurePolicy: Fail
  name: mcnset.kb.io
  rules:
  - apiGroups:
    - core.matrixorigin.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - cnsets
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: '{{ .Release.Namespace }}'
      path: /mutate-core-matrixorigin-io-v1alpha1-dnset
  failurePolicy: Fail
  name: mdnset.kb.io
  rules:
  - apiGroups:
    - core.matrixorigin.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - dnsets
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: '{{ .Release.Namespace }}'
      path: /mutate-core-matrixorigin-io-v1alpha1-logset
  failurePolicy: Fail
  name: mlogset.kb.io
  rules:
  - apiGroups:
    - core.matrixorigin.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - logsets
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: '{{ .Release.Namespace }}'
      path: /mutate-core-matrixorigin-io-v1alpha1-matrixonecluster
  failurePolicy: Fail
  name: mmatrixonecluster.kb.io
  rules:
  - apiGroups:
    - core.matrixorigin.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - matrixoneclusters
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: '{{ .Release.Namespace }}'
      path: /mutate-core-matrixorigin-io-v1alpha1-proxyset
  failurePolicy: Fail
  name: mproxyset.kb.io
  rules:
  - apiGroups:
    - core.matrixorigin.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - proxysets
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: matrixone-operator-validating-webhook-{{ .Release.Name }}
  annotations:
    matrixorigin.io/ca-injection: 'y'
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: '{{ .Release.Namespace }}'
      path: /validate-core-matrixorigin-io-v1alpha1-cnset
  failurePolicy: Fail
  name: vcnset.kb.io
  rules:
  - apiGroups:
    - core.matrixorigin.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - cnsets
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: '{{ .Release.Namespace }}'
      path: /validate-core-matrixorigin-io-v1alpha1-dnset
  failurePolicy: Fail
  name: vdnset.kb.io
  rules:
  - apiGroups:
    - core.matrixorigin.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - dnsets
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: '{{ .Release.Namespace }}'
      path: /validate-core-matrixorigin-io-v1alpha1-logset
  failurePolicy: Fail
  name: vlogset.kb.io
  rules:
  - apiGroups:
    - core.matrixorigin.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - logsets
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: '{{ .Release.Namespace }}'
      path: /validate-core-matrixorigin-io-v1alpha1-matrixonecluster
  failurePolicy: Fail
  name: vmatrixonecluster.kb.io
  rules:
  - apiGroups:
    - core.matrixorigin.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - matrixoneclusters
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: '{{ .Release.Namespace }}'
      path: /validate-core-matrixorigin-io-v1alpha1-proxyset
  failurePolicy: Fail
  name: vproxyset.kb.io
  rules:
  - apiGroups:
    - core.matrixorigin.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - proxysets
  sideEffects: None
