name: helm_check
description: "helm package install check"

runs:
  using: "composite"

  steps:
    - name: prepare cluster
      uses: ./.github/actions/cluster

    - name: setup helm
      uses: azure/setup-helm@v1
      with:
        version: '${{ env.helm-version }}'

    - name: install mo cluster with helm
      shell: bash
      run: |
        helm install mo-op charts/matrixone-operator

    - name: Run test
      shell: bash
      run:  |
        ./hack/e2e.sh
